module.exports = [
  // ================= WOMEN'S FASHION =================
  {
    name: 'Floral Print Silk Summer Wrap Dress',
    brand: 'StyleAura',
    category: 'Women',
    subcategory: 'Dresses',
    gender: 'Women',
    description: 'Elegant V-neck wrap midi dress in lightweight breathable viscose with vibrant floral pattern.',
    price: 1499,
    originalPrice: 2999,
    discountPercentage: 50,
    rating: 4.8,
    numReviews: 240,
    salesCount: 650,
    stock: 35,
    images: ['https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600'],
    isTrending: true,
    tags: ['Floral', 'Summer', 'Casual', 'Maxi', 'Dress'],
    variants: [
      { variantId: 'v1', size: 'S', color: 'Floral Red', stock: 15, price: 1499, sku: 'DRE-RED-S' },
      { variantId: 'v2', size: 'M', color: 'Floral Red', stock: 20, price: 1499, sku: 'DRE-RED-M' },
    ],
  },
  {
    name: 'Emerald Satin Party Bodycon Dress',
    brand: 'Glamora',
    category: 'Women',
    subcategory: 'Dresses',
    gender: 'Women',
    description: 'Sleek satin bodycon mini dress featuring ruched side detail and adjustable spaghetti straps.',
    price: 2199,
    originalPrice: 4399,
    discountPercentage: 50,
    rating: 4.7,
    numReviews: 180,
    salesCount: 410,
    stock: 25,
    images: ['https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600'],
    isTrending: true,
    tags: ['Satin', 'Party', 'Bodycon', 'Mini', 'Nightout'],
    variants: [
      { variantId: 'v1', size: 'S', color: 'Emerald Green', stock: 10, price: 2199, sku: 'DRE-EME-S' },
      { variantId: 'v2', size: 'M', color: 'Emerald Green', stock: 15, price: 2199, sku: 'DRE-EME-M' },
    ],
  },
  {
    name: 'Bohemian Tiered Maxi Summer Dress',
    brand: 'UrbanMuse',
    category: 'Women',
    subcategory: 'Dresses',
    gender: 'Women',
    description: 'Flowy tiered maxi dress crafted from 100% organic cotton with ruffle sleeves.',
    price: 1899,
    originalPrice: 3499,
    discountPercentage: 45,
    rating: 4.9,
    numReviews: 310,
    salesCount: 520,
    stock: 30,
    images: ['https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600'],
    isTrending: true,
    tags: ['Maxi', 'Boho', 'Summer', 'Cotton'],
    variants: [
      { variantId: 'v1', size: 'M', color: 'Mustard Yellow', stock: 15, price: 1899, sku: 'DRE-MUS-M' },
      { variantId: 'v2', size: 'L', color: 'Mustard Yellow', stock: 15, price: 1899, sku: 'DRE-MUS-L' },
    ],
  },
  {
    name: 'Ribbed Knit Cropped Tank Top',
    brand: 'DailyDrip',
    category: 'Women',
    subcategory: 'Tops',
    gender: 'Women',
    description: 'Soft stretch ribbed cotton crop top designed for casual everyday layering.',
    price: 699,
    originalPrice: 1299,
    discountPercentage: 46,
    rating: 4.5,
    numReviews: 120,
    salesCount: 780,
    stock: 50,
    images: ['https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600'],
    isTrending: false,
    tags: ['Crop Top', 'Basics', 'Cotton', 'T-Shirts'],
    variants: [
      { variantId: 'v1', size: 'S', color: 'Off White', stock: 25, price: 699, sku: 'TOP-WHT-S' },
      { variantId: 'v2', size: 'M', color: 'Off White', stock: 25, price: 699, sku: 'TOP-WHT-M' },
    ],
  },
  {
    name: 'Oversized Boyfriend Denim Shirt',
    brand: 'StreetMode',
    category: 'Women',
    subcategory: 'Tops',
    gender: 'Women',
    description: 'Relaxed fit vintage wash denim shirt with dropped shoulders and chest flap pockets.',
    price: 1599,
    originalPrice: 2999,
    discountPercentage: 47,
    rating: 4.6,
    numReviews: 95,
    salesCount: 340,
    stock: 20,
    images: ['https://images.unsplash.com/photo-1598554747436-c9293d6a588f?w=600'],
    isTrending: false,
    tags: ['Denim', 'Shirt', 'Oversized', 'Streetwear'],
    variants: [
      { variantId: 'v1', size: 'M', color: 'Medium Wash', stock: 10, price: 1599, sku: 'SHI-DEN-M' },
      { variantId: 'v2', size: 'L', color: 'Medium Wash', stock: 10, price: 1599, sku: 'SHI-DEN-L' },
    ],
  },

  // ================= WOMEN ETHNIC WEAR =================
  {
    name: 'Handcrafted Chanderi Silk Saree with Blouse',
    brand: 'Eleganza',
    category: 'Ethnic Wear',
    subcategory: 'Sarees',
    gender: 'Women',
    description: 'Traditional Chanderi silk saree with zari weave borders and matching unstitched blouse piece.',
    price: 3499,
    originalPrice: 6999,
    discountPercentage: 50,
    rating: 4.9,
    numReviews: 450,
    salesCount: 890,
    stock: 15,
    images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600'],
    isTrending: true,
    tags: ['Saree', 'Silk', 'Ethnic', 'Festive', 'Traditional'],
    variants: [
      { variantId: 'v1', size: 'Free Size', color: 'Royal Blue', stock: 15, price: 3499, sku: 'SAR-BLU' },
    ],
  },
  {
    name: 'Anarkali Embroidered Kurta Set',
    brand: 'FashionNest',
    category: 'Ethnic Wear',
    subcategory: 'Kurtis',
    gender: 'Women',
    description: 'Floor-length flared cotton Anarkali suit set with heavy Dupatta and palazzo trousers.',
    price: 2499,
    originalPrice: 4999,
    discountPercentage: 50,
    rating: 4.8,
    numReviews: 290,
    salesCount: 620,
    stock: 25,
    images: ['https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600'],
    isTrending: true,
    tags: ['Kurti', 'Anarkali', 'Ethnic', 'Suit', 'Festive'],
    variants: [
      { variantId: 'v1', size: 'M', color: 'Maroon', stock: 12, price: 2499, sku: 'KUR-MAR-M' },
      { variantId: 'v2', size: 'L', color: 'Maroon', stock: 13, price: 2499, sku: 'KUR-MAR-L' },
    ],
  },
  {
    name: 'Georgette Designer Printed Lehenga Choli',
    brand: 'LuxeLane',
    category: 'Ethnic Wear',
    subcategory: 'Lehengas',
    gender: 'Women',
    description: 'Semi-stitched designer printed georgette lehenga with sequin blouse piece and net dupatta.',
    price: 4599,
    originalPrice: 8999,
    discountPercentage: 49,
    rating: 4.9,
    numReviews: 180,
    salesCount: 390,
    stock: 12,
    images: ['https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=600'],
    isTrending: true,
    tags: ['Lehenga', 'Wedding', 'Festive', 'Ethnic'],
    variants: [
      { variantId: 'v1', size: 'Free Size', color: 'Blush Pink', stock: 12, price: 4599, sku: 'LEH-PNK' },
    ],
  },

  // ================= WOMEN BOTTOM WEAR =================
  {
    name: 'High-Waist Wide Leg Straight Jeans',
    brand: 'Trendora',
    category: 'Women',
    subcategory: 'Bottom Wear',
    gender: 'Women',
    description: 'Classic 90s vintage style non-stretch wide leg denim pants with raw hem detail.',
    price: 1799,
    originalPrice: 3299,
    discountPercentage: 45,
    rating: 4.7,
    numReviews: 210,
    salesCount: 540,
    stock: 30,
    images: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600'],
    isTrending: true,
    tags: ['Jeans', 'Denim', 'Wide Leg', 'High Waist'],
    variants: [
      { variantId: 'v1', size: '28', color: 'Light Blue', stock: 15, price: 1799, sku: 'JEA-BLU-28' },
      { variantId: 'v2', size: '30', color: 'Light Blue', stock: 15, price: 1799, sku: 'JEA-BLU-30' },
    ],
  },
  {
    name: 'Pleated A-Line Midi Skirt',
    brand: 'ModaCraft',
    category: 'Women',
    subcategory: 'Bottom Wear',
    gender: 'Women',
    description: 'High-waisted metallic shine accordion pleated skirt with comfortable elastic waistband.',
    price: 1399,
    originalPrice: 2599,
    discountPercentage: 46,
    rating: 4.6,
    numReviews: 85,
    salesCount: 290,
    stock: 20,
    images: ['https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600'],
    isTrending: false,
    tags: ['Skirt', 'Midi', 'Pleated', 'Party'],
    variants: [
      { variantId: 'v1', size: 'S', color: 'Champagne Gold', stock: 10, price: 1399, sku: 'SKI-GLD-S' },
      { variantId: 'v2', size: 'M', color: 'Champagne Gold', stock: 10, price: 1399, sku: 'SKI-GLD-M' },
    ],
  },

  // ================= WOMEN FOOTWEAR =================
  {
    name: 'Stiletto Strappy High Heels',
    brand: 'Glamora',
    category: 'Footwear',
    subcategory: 'Heels',
    gender: 'Women',
    description: '3.5 inch elegant ankle strap stiletto heels featuring square open toe silhouette.',
    price: 2299,
    originalPrice: 4599,
    discountPercentage: 50,
    rating: 4.8,
    numReviews: 165,
    salesCount: 410,
    stock: 18,
    images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600'],
    isTrending: true,
    tags: ['Heels', 'Stilettos', 'Party', 'Footwear'],
    variants: [
      { variantId: 'v1', size: '37', color: 'Nude Beige', stock: 9, price: 2299, sku: 'HEE-BEI-37' },
      { variantId: 'v2', size: '38', color: 'Nude Beige', stock: 9, price: 2299, sku: 'HEE-BEI-38' },
    ],
  },
  {
    name: 'Comfy Platform Wedge Sandals',
    brand: 'EliteWalk',
    category: 'Footwear',
    subcategory: 'Sandals',
    gender: 'Women',
    description: 'Espadrille woven wedge platform sandals with memory foam cushioned footbed.',
    price: 1899,
    originalPrice: 3499,
    discountPercentage: 45,
    rating: 4.7,
    numReviews: 140,
    salesCount: 380,
    stock: 22,
    images: ['https://images.unsplash.com/photo-1562273138-f46be4ebdf33?w=600'],
    isTrending: false,
    tags: ['Wedges', 'Sandals', 'Summer', 'Flats'],
    variants: [
      { variantId: 'v1', size: '37', color: 'Tan', stock: 11, price: 1899, sku: 'WED-TAN-37' },
      { variantId: 'v2', size: '38', color: 'Tan', stock: 11, price: 1899, sku: 'WED-TAN-38' },
    ],
  },

  // ================= JEWELLERY & ACCESSORIES =================
  {
    name: '18K Gold Plated Chunky Hoop Earrings',
    brand: 'LuxeLane',
    category: 'Jewellery',
    subcategory: 'Earrings',
    gender: 'Women',
    description: 'Hypoallergenic lightweight gold-plated thick hoop earrings designed for daily wear & party glamour.',
    price: 999,
    originalPrice: 1999,
    discountPercentage: 50,
    rating: 4.9,
    numReviews: 285,
    salesCount: 750,
    stock: 40,
    images: ['https://images.unsplash.com/photo-1630019852942-f89202989a59?w=600'],
    isTrending: true,
    tags: ['Earrings', 'Gold', 'Jewellery', 'Hoops'],
    variants: [
      { variantId: 'v1', size: '25mm', color: 'Glossy Gold', stock: 20, price: 999, sku: 'EAR-GLD-25' },
      { variantId: 'v2', size: '30mm', color: 'Glossy Gold', stock: 20, price: 999, sku: 'EAR-GLD-30' },
    ],
  },
  {
    name: 'Sparkling Crystal Drop Dangle Earrings',
    brand: 'Glamora',
    category: 'Jewellery',
    subcategory: 'Earrings',
    gender: 'Women',
    description: 'Elegant chandelier crystal dangle earrings featuring cubic zirconia stones for festive occasions.',
    price: 1299,
    originalPrice: 2599,
    discountPercentage: 50,
    rating: 4.8,
    numReviews: 190,
    salesCount: 420,
    stock: 25,
    images: ['https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600'],
    isTrending: true,
    tags: ['Earrings', 'Crystal', 'Dangle', 'Jewellery'],
    variants: [
      { variantId: 'v1', size: 'Standard', color: 'Diamond Silver', stock: 15, price: 1299, sku: 'EAR-SLV' },
      { variantId: 'v2', size: 'Standard', color: 'Rose Gold', stock: 10, price: 1299, sku: 'EAR-ROS' },
    ],
  },
  {
    name: 'Sterling Silver Layered Pendant Necklace',
    brand: 'StyleAura',
    category: 'Jewellery',
    subcategory: 'Necklaces',
    gender: 'Women',
    description: '925 Sterling Silver dual-layered chain necklace with polished coin and crystal star pendants.',
    price: 1799,
    originalPrice: 3499,
    discountPercentage: 48,
    rating: 4.9,
    numReviews: 340,
    salesCount: 510,
    stock: 18,
    images: ['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600'],
    isTrending: true,
    tags: ['Necklace', 'Silver', 'Jewellery', 'Pendant'],
    variants: [
      { variantId: 'v1', size: '18 Inch', color: 'Silver', stock: 18, price: 1799, sku: 'NEC-SLV-18' },
    ],
  },
  {
    name: 'Classic Freshwater Pearl Stud Earrings Pair',
    brand: 'Eleganza',
    category: 'Jewellery',
    subcategory: 'Earrings',
    gender: 'Women',
    description: 'Genuine AAA quality round freshwater cultured pearl stud earrings with 925 sterling silver posts.',
    price: 1199,
    originalPrice: 2399,
    discountPercentage: 50,
    rating: 4.9,
    numReviews: 410,
    salesCount: 720,
    stock: 30,
    images: ['https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=600'],
    isTrending: true,
    tags: ['Pearl', 'Earrings', 'Jewellery', 'Studs'],
    variants: [
      { variantId: 'v1', size: '8mm', color: 'Ivory White', stock: 30, price: 1199, sku: 'PEA-WHT-8' },
    ],
  },
  {
    name: 'Italian Grain Leather Crossbody Tote Bag',
    brand: 'ModaCraft',
    category: 'Accessories',
    subcategory: 'Handbags',
    gender: 'Women',
    description: 'Handcrafted genuine leather handbag with multi-zip compartments, gold hardware, and detachable shoulder strap.',
    price: 3899,
    originalPrice: 6999,
    discountPercentage: 44,
    rating: 4.9,
    numReviews: 156,
    salesCount: 430,
    isTrending: true,
    tags: ['Handbag', 'Tote', 'Leather', 'Bag'],
    variants: [
      { variantId: 'v1', size: 'Medium', color: 'Tan Brown', stock: 10, price: 3899, sku: 'BAG-TAN-M' },
      { variantId: 'v2', size: 'Medium', color: 'Classic Black', stock: 10, price: 3899, sku: 'BAG-BLK-M' },
    ],
  },
  {
    name: 'Classic Aviator Polarized Sunglasses',
    brand: 'UrbanEdge',
    category: 'Accessories',
    subcategory: 'Sunglasses',
    gender: 'Unisex',
    description: '100% UV400 protection metal frame aviator sunglasses with gradient anti-glare lenses.',
    price: 1499,
    originalPrice: 2999,
    discountPercentage: 50,
    rating: 4.7,
    numReviews: 240,
    salesCount: 520,
    isTrending: true,
    tags: ['Sunglasses', 'Aviators', 'Accessories', 'Eyewear'],
    variants: [
      { variantId: 'v1', size: 'Standard', color: 'Gold / Dark Green', stock: 20, price: 1499, sku: 'SUN-GLD' },
      { variantId: 'v2', size: 'Standard', color: 'Silver / Black', stock: 15, price: 1499, sku: 'SUN-SLV' },
    ],
  },

  // ================= MEN'S FASHION =================
  {
    name: 'Classic Slim Fit Oxford Cotton Shirt',
    brand: 'VibeWear',
    category: 'Men',
    subcategory: 'Shirts',
    gender: 'Men',
    description: '100% breathable Oxford cotton casual button-down shirt with buttoned collar and curved hemline.',
    price: 1299,
    originalPrice: 2499,
    discountPercentage: 48,
    rating: 4.6,
    numReviews: 190,
    salesCount: 580,
    stock: 40,
    images: ['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600'],
    isTrending: true,
    tags: ['Shirt', 'Cotton', 'Casual', 'Formal', 'Men'],
    variants: [
      { variantId: 'v1', size: 'M', color: 'Sky Blue', stock: 20, price: 1299, sku: 'SHI-BLU-M' },
      { variantId: 'v2', size: 'L', color: 'Sky Blue', stock: 20, price: 1299, sku: 'SHI-BLU-L' },
    ],
  },
  {
    name: 'Heavyweight Graphic Crewneck Hoodie',
    brand: 'StreetMode',
    category: 'Men',
    subcategory: 'Hoodies',
    gender: 'Men',
    description: 'Fleece lined 350 GSM cotton blend pullover hoodie with kangaroo pouch pocket.',
    price: 1999,
    originalPrice: 3899,
    discountPercentage: 49,
    rating: 4.8,
    numReviews: 270,
    salesCount: 640,
    stock: 30,
    images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600'],
    isTrending: true,
    tags: ['Hoodie', 'Sweatshirt', 'Fleece', 'Streetwear'],
    variants: [
      { variantId: 'v1', size: 'L', color: 'Charcoal Black', stock: 15, price: 1999, sku: 'HOO-BLK-L' },
      { variantId: 'v2', size: 'XL', color: 'Charcoal Black', stock: 15, price: 1999, sku: 'HOO-BLK-XL' },
    ],
  },
  {
    name: 'Slim Fit Stretch Chino Trousers',
    brand: 'UrbanEdge',
    category: 'Men',
    subcategory: 'Bottom Wear',
    gender: 'Men',
    description: 'Versatile cotton stretch chinos engineered for flexible movement from office to weekend.',
    price: 1699,
    originalPrice: 3199,
    discountPercentage: 47,
    rating: 4.7,
    numReviews: 210,
    salesCount: 490,
    stock: 35,
    images: ['https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600'],
    isTrending: false,
    tags: ['Chinos', 'Trousers', 'Pants', 'Formal', 'Men'],
    variants: [
      { variantId: 'v1', size: '32', color: 'Beige Khaki', stock: 18, price: 1699, sku: 'CHI-KHA-32' },
      { variantId: 'v2', size: '34', color: 'Beige Khaki', stock: 17, price: 1699, sku: 'CHI-KHA-34' },
    ],
  },
  {
    name: 'Men Kurta with Embroidered Nehru Jacket',
    brand: 'FashionNest',
    category: 'Men',
    subcategory: 'Ethnic Wear',
    gender: 'Men',
    description: 'Dupion silk blend knee-length kurta with Churidar pants and contrasting silk Nehru jacket.',
    price: 3299,
    originalPrice: 6499,
    discountPercentage: 49,
    rating: 4.9,
    numReviews: 320,
    salesCount: 710,
    stock: 20,
    images: ['https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600'],
    isTrending: true,
    tags: ['Kurta', 'Nehru Jacket', 'Ethnic', 'Festive', 'Men'],
    variants: [
      { variantId: 'v1', size: '40', color: 'Off White / Gold', stock: 10, price: 3299, sku: 'KUR-GLD-40' },
      { variantId: 'v2', size: '42', color: 'Off White / Gold', stock: 10, price: 3299, sku: 'KUR-GLD-42' },
    ],
  },
  {
    name: 'Ultralight Horizon Running Shoes',
    brand: 'EliteWalk',
    category: 'Footwear',
    subcategory: 'Sneakers',
    gender: 'Men',
    description: 'High-performance breathable running shoes with responsive cushioning and ergonomic arch support.',
    price: 2999,
    originalPrice: 5999,
    discountPercentage: 50,
    rating: 4.8,
    numReviews: 124,
    salesCount: 850,
    stock: 25,
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600'],
    isTrending: true,
    tags: ['Shoes', 'Sneakers', 'Running', 'Sports', 'Footwear'],
    variants: [
      { variantId: 'v1', size: 'US 8', color: 'Neon Red', stock: 10, price: 2999, sku: 'SHO-RED-8' },
      { variantId: 'v2', size: 'US 9', color: 'Neon Red', stock: 15, price: 2999, sku: 'SHO-RED-9' },
    ],
  },
  {
    name: 'Handcrafted Genuine Leather Loafers',
    brand: 'ModaCraft',
    category: 'Footwear',
    subcategory: 'Formal Shoes',
    gender: 'Men',
    description: 'Premium Italian calfskin slip-on loafers with cushioned leather lining and durable rubber sole.',
    price: 3699,
    originalPrice: 6999,
    discountPercentage: 47,
    rating: 4.8,
    numReviews: 195,
    salesCount: 420,
    stock: 16,
    images: ['https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=600'],
    isTrending: false,
    tags: ['Loafers', 'Formal', 'Leather', 'Footwear'],
    variants: [
      { variantId: 'v1', size: 'UK 8', color: 'Deep Cognac', stock: 8, price: 3699, sku: 'LOA-COG-8' },
      { variantId: 'v2', size: 'UK 9', color: 'Deep Cognac', stock: 8, price: 3699, sku: 'LOA-COG-9' },
    ],
  },
  {
    name: 'Minimalist Chronograph Rose Gold Watch',
    brand: 'LuxeLane',
    category: 'Accessories',
    subcategory: 'Watches',
    gender: 'Men',
    description: 'Sleek stainless steel case analog watch with sapphire crystal glass and genuine leather strap.',
    price: 4499,
    originalPrice: 8999,
    discountPercentage: 50,
    rating: 4.8,
    numReviews: 310,
    salesCount: 580,
    stock: 14,
    images: ['https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=600'],
    isTrending: true,
    tags: ['Watch', 'Accessories', 'Chronograph', 'Leather'],
    variants: [
      { variantId: 'v1', size: '40mm', color: 'Rose Gold / Brown', stock: 8, price: 4499, sku: 'WAT-ROS-40' },
      { variantId: 'v2', size: '40mm', color: 'Silver / Black', stock: 6, price: 4499, sku: 'WAT-SLV-40' },
    ],
  },

  // ================= KIDS FASHION =================
  {
    name: 'Girls Princess Tulle Party Dress',
    brand: 'FashionNest',
    category: 'Kids',
    subcategory: 'Girls Wear',
    gender: 'Kids',
    description: 'Soft cotton lined sequin bow tulle frock dress designed for birthday celebrations.',
    price: 1199,
    originalPrice: 2399,
    discountPercentage: 50,
    rating: 4.9,
    numReviews: 140,
    salesCount: 390,
    stock: 25,
    images: ['https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=600'],
    isTrending: true,
    tags: ['Kids', 'Dress', 'Girls', 'Frock', 'Party'],
    variants: [
      { variantId: 'v1', size: '3-4Y', color: 'Pink', stock: 12, price: 1199, sku: 'KID-PNK-3' },
      { variantId: 'v2', size: '5-6Y', color: 'Pink', stock: 13, price: 1199, sku: 'KID-PNK-5' },
    ],
  },
  {
    name: 'Boys Cotton Graphic Printed T-Shirt & Shorts Set',
    brand: 'DailyDrip',
    category: 'Kids',
    subcategory: 'Boys Wear',
    gender: 'Kids',
    description: '100% breathable organic cotton crewneck tee and elasticated drawstring denim shorts combo.',
    price: 899,
    originalPrice: 1799,
    discountPercentage: 50,
    rating: 4.7,
    numReviews: 95,
    salesCount: 460,
    stock: 30,
    images: ['https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=600'],
    isTrending: false,
    tags: ['Kids', 'Boys', 'T-Shirt', 'Shorts', 'Cotton'],
    variants: [
      { variantId: 'v1', size: '4-5Y', color: 'Blue / Yellow', stock: 15, price: 899, sku: 'KID-TSH-4' },
      { variantId: 'v2', size: '6-7Y', color: 'Blue / Yellow', stock: 15, price: 899, sku: 'KID-TSH-6' },
    ],
  },

  // ================= BEAUTY & CARE =================
  {
    name: 'Velvet Matte Longwearing Lipstick',
    brand: 'Glamora',
    category: 'Beauty',
    subcategory: 'Makeup',
    gender: 'Women',
    description: 'Hydrating 16-hour transfer-proof velvet matte lipstick infused with Vitamin E & Argan Oil.',
    price: 699,
    originalPrice: 1299,
    discountPercentage: 46,
    rating: 4.8,
    numReviews: 530,
    salesCount: 1200,
    stock: 50,
    images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600'],
    isTrending: true,
    tags: ['Lipstick', 'Makeup', 'Beauty', 'Matte'],
    variants: [
      { variantId: 'v1', size: '4.2g', color: 'Ruby Red', stock: 25, price: 699, sku: 'LIP-RED' },
      { variantId: 'v2', size: '4.2g', color: 'Nude Rose', stock: 25, price: 699, sku: 'LIP-NUD' },
    ],
  },
  {
    name: 'Luminous Glow Serum Foundation',
    brand: 'LuxeLane',
    category: 'Beauty',
    subcategory: 'Skincare',
    gender: 'Women',
    description: 'Lightweight buildable medium coverage liquid foundation with SPF 30 & Hyaluronic Acid.',
    price: 1199,
    originalPrice: 2199,
    discountPercentage: 45,
    rating: 4.7,
    numReviews: 290,
    salesCount: 680,
    stock: 35,
    images: ['https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600'],
    isTrending: true,
    tags: ['Foundation', 'Makeup', 'Beauty', 'Skincare'],
    variants: [
      { variantId: 'v1', size: '30ml', color: 'Warm Ivory', stock: 18, price: 1199, sku: 'FON-IVO' },
      { variantId: 'v2', size: '30ml', color: 'Natural Beige', stock: 17, price: 1199, sku: 'FON-BEI' },
    ],
  },
  {
    name: 'French Velvet Rose Eau De Parfum (100ml)',
    brand: 'Eleganza',
    category: 'Beauty',
    subcategory: 'Fragrance',
    gender: 'Unisex',
    description: 'Luxurious long-lasting floral oriental fragrance with notes of Damask Rose, Vanilla, & Amber.',
    price: 2499,
    originalPrice: 4999,
    discountPercentage: 50,
    rating: 4.9,
    numReviews: 380,
    salesCount: 890,
    stock: 25,
    images: ['https://images.unsplash.com/photo-1541643600914-78b084683601?w=600'],
    isTrending: true,
    tags: ['Perfume', 'Fragrance', 'Beauty', 'Rose'],
    variants: [
      { variantId: 'v1', size: '100ml', color: 'Glass Bottle', stock: 25, price: 2499, sku: 'PER-ROS-100' },
    ],
  },
];
